### ISSUE TITLE
Invite Link needs to be fixed 

### ISSUE THREAD

**Issue by talinger** [TheCodingDen/highlights#50]
The invite link on your github page is
https://discord.com/api/oauth2/authorize?client_id=740802975576096829&scope=bot

it adds the bot but the bot won't show up for slash commands.

I got help getting a link that fixed the scope in the support server you have linked, so I'm good! But it will probably help future people.

also idk if you know but carlbot just disabled its highlight feature for anyone without manage messages permissions.
so people are going to be looking for alternatives again. that's how I found you.

**Comment by ThatsNoMoon** [comment]
Thanks for pointing that out!
