### ISSUE TITLE
Using `/remove` on a channel-specific keyword does not remove keyword

### ISSUE THREAD

**Issue by ariscript** [TheCodingDen/highlights#62]
**Description of bug**
Adding a keyword for a specific channel, and then attempting to remove it later reports as not having that keyword set.

**To Reproduce**
List the steps taken to produce the bug:
1. Use command `/add <keyword> <channel>`
2. Use command `/remove <keyword>`

**Expected behavior**
If the keyword is just registered in one channel, remove the keyword.
If the keyword is registered in multiple channels, one of the following:
- Prompt me with which channels to remove with buttons/dropdown/something
- Edit the `/remove` command to optionally take a `channel` argument
- Remove all occurrences of the keyword in all channels

**Screenshots**
Example with keyword set in just one channel:
![image](https://user-images.githubusercontent.com/57048370/189548438-9becfb2b-15f8-49ee-859b-f7d197695647.png)

Example with keyword set in multiple channels:
![image](https://user-images.githubusercontent.com/57048370/189548414-7487b20c-aca2-4fdb-9d30-173c9c47c52d.png)

**Comment by ThatsNoMoon** [comment]
You need to (and already can) specify the channel from which to remove the keyword to remove a channel-specific keyword.
![image](https://user-images.githubusercontent.com/25443950/190925847-076b4687-fe7b-43e6-9b48-845c8f05e69a.png)
